import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="contianer">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex text-center justify-center mt-10 text-2xl">
        <h1>Hello World</h1>
      </main>
    </div>
  );
};

export default Home;
